Remove incompatible @register.filter w/ @mark_safe
It seems that both cannot be used in the correct order, which would be

    @register.filter
    @mark_safe
    def somefiler(x):
        pass

Because otherwise the following error occurs

    django.template.exceptions.TemplateSyntaxError: somefilter requires 0 arguments, 1 provided

This has not been an issue with Django <2